import = [
	"~/.config/alacritty/themes/onedark/theme.toml"
]

[cursor]
style = {blinking="On"}

[font]
normal = {family="JetBrainsMono Nerd Font", style="Regular"}
size=10

[window]
#padding = {x=10, y=10}
