#!/bin/bash

# Autostart apps, do reopen while bspwm reload
/usr/lib64/polkit-gnome/polkit-gnome-authentication-agent-1 & # Polkit dont reopen
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom &
$HOME/.config/polybar/launch.sh &


# Apps for autostart, dont reopen
# TODO: Dont work with bitwarden-dekstop, blueman-manager
applications=(
	"blueman-manager"
	"yandex-music"
	"notion-app"
	"bitwarden-desktop"
	# "firefox"
	"telegram-desktop"
	"flameshot"
)

for app in "${applications[@]}"; do
  if pgrep -f "$app" > /dev/null; then
		echo "$app already running, skip"
  else
    echo "Start $app"
    "$app" &
  fi
done

# Displays resolution
xrandr --output DVI-D-0 --off --output HDMI-0 --off --output DP-0 --off --output DP-1 --off --output DP-2 --mode 1920x1080 --pos 0x180 --rotate normal --output DP-3 --off --output DP-4 --primary --mode 2560x1440 --pos 1920x0 --rotate normal --output DP-5 --off &

# Restore wallpapers
nitrogen --restore &

# Keyboard layout switch
$HOME/.config/bspwm/scripts/layout_switch.sh

# Workspaces
bspc monitor DP-2 -d 1 2
bspc monitor DP-4 -d 3 4 5

# Appearance, colors
bspc config border_width        2
bspc config window_gap          6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#23252e"
# bspc config active_border_color "#BD93F9"
bspc config focused_border_color "#98c379"
bspc config presel_feedback_color "#23252e"


# Rules apps
bspc rule -a Pavucontrol state=floating monitor="DP-4" rectangle="900x450+500+210"
bspc rule -a Blueman-manager state=floating monitor="DP-4" rectangle="600x250+1310+212"
bspc rule -a Google-chrome desktop='^1'
bspc rule -a firefox desktop='^1'
bspc rule -a YandexMusic desktop='^2'
bspc rule -a TelegramDesktop desktop='^2'
bspc rule -a Notion desktop='^2'
bspc rule -a Bitwarden state=floating monitor="DP-4"

